### PR TITLE
final changes for demo

### LINKED ISSUE #16: remove testing timer, use callbacks to indicate when likes and comments are done to take next photo
## Description

Please provide a detailed description of the proposed feature or enhancement.

## Helpful Documentation

Please list any documentation or resources that may be helpful.

- [ ] Documentation A
- [ ] Documentation B

### PR DESCRIPTION
**Pull request by natapokie**
## Description

**Fixes #16 #18 #30  **

adding mock data for testing when API is down. in order to use mock data, add the following variable to your `.env` file,
```
USE_MOCK_DATA=true // set variable to any non empty string to use mock data
USE_MOCK_DATA='' // to turn off mock data on errors use an empty string
```

- [x] removing testing timer -- make sure photos are taken based on when the likes and comments animation are done
- [x] cleaning up ui so it's only the likes and comment components
- [x] implementing callback functions in likes and comments to indicate when animations complete
  - [x] ~~likes component (@vicliu2001)~~
  - [x] comments component (@viiiiiicccky)
- [x] loading overlay to indicate when photo is being taken
  - [x] simple animations
- [x] loading spinner displayed when waiting for API response
- [x] handling "no person" or API response error

## Documentation Used

Please list any documentation or resources that were referenced while making these changes.

- [countdown timer reference](https://volerelife.wordpress.com/2023/01/03/how-to-create-a-countdown-timer-with-react-hooks-v2/)
- [spinner with tailwind css](https://tw-elements.com/docs/react/components/spinners/)

## Issues Faced and Resolutions

Please describe any issues you encountered during development and how you resolved them.

- Issue: Description of the issue
    - Resolution: Steps taken to resolve the issue

## How To Test?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- callback for comments: check last comment is displayed before taking a new picture. see screenshot

## Screenshots (if applicable):

- callback for comments:
Screenshot 2024-08-30 at 12 01 51 PM
Screenshot 2024-08-30 at 12 02 18 PM

- loading overlay animations
https://github.com/user-attachments/assets/de49af80-28e7-4508-80cb-47da9355bd5a

### CODE REVIEW

**Review by eriysd — APPROVED** [review]
Lgtm!

**Review by eriysd — APPROVED** [review]
Lgtm:)

**Review by vicliu2001 — APPROVED** [review]
looks good

**Review by viiiiiicccky — APPROVED** [review]
lgtm!

**Pull request merged**
