### PR TITLE
51 set up https server instead of http server for local development

### LINKED ISSUE #51: set up https server instead of http server for local development
## Description

Please provide a detailed description of the proposed feature or enhancement.

## Helpful Documentation

Please list any documentation or resources that may be helpful.

- [ ] Documentation A
- [ ] Documentation B

### PR DESCRIPTION
**Pull request by viiiiiicccky**
## Description

**Fixes #51 **

1. Replaced http with https in server.ts, using a self-signed SSL certificate for local development.
2. Current Status:
    - On the laptop browser, the app works with HTTPS as expected, and images are saved to the server.
    - On iPad Safari, the app can access the URL and display the interface over HTTPS, but image saving to server/__uploads fails.

## Documentation Used

Please list any documentation or resources that were referenced while making these changes.

- [[ ] Documentation A](https://stackoverflow.com/questions/5734323/ipad-safari-development-toolbar)
- [ ] Documentation B

## Issues Faced and Resolutions

Please describe any issues you encountered during development and how you resolved them.

- Issue 1:  Client couldn’t connect to the server with HTTPS initially due to the configuration setup
    - resolution: Updated `scripts` in `package.json` to use `dev: node server.js`, and created `server.js` to handle HTTPS setup.
- Issue 2: The iPad can access the app at `https://<ip_address>:3000` but fails to save images to server/__uploads. The server does not receive or log the upload requests from the iPad.
    - resolution: in .env, modify the below urls to use https and ip addresses!
    ```
    CLIENT_BASE_URL=https://10.0.0.21:3000
    SERVER_BASE_URL=https://10.0.0.21:8080
     ```
- Issue 3 (Unresolved): Unable to open the developer/inspection mode for iPad Safari to direct debug...
- Issue 4 (Unresolved): Using Postman on the iPad to test the endpoint results in a 30-second timeout.
- Issue 5 (Unresolved):  Logging added in the client does not show up for both iPad and laptop

## How To Test?
**Generating Certificates**
1. Using `mkcert`
- To install `mkcert`
    - for MAC: run `brew install mkcert`and `mkcert -install`
    - for Windows: download latest release https://github.com/FiloSottile/mkcert/releases, and run `mkcert -install`
- At root of the repo, create an ssl folder `mkdir ssl` and `cd ssl`
- Generate certificate and key for a specific IP address: 
`mkcert -key-file <ip-address>-key.pem -cert-file <ip-address>.pem <ip-address>`
- NOTE: If your local IP address changes, you’ll need to regenerate the SSL certificate and key files to match your new IP address!
2. Using OpenSSL (alternative)

**Configure .env for the SSL Paths**
```
SSL_KEY_PATH=./ssl/<ip-address>-key.pem
SSL_CERT_PATH=./ssl/<ip-address>.pem
```

**Optional: iPad Certificate Transfer and Trust**
To prevent warnings on the iPad, you can transfer the generated certificate to the iPad and enable trust under Settings > General > About > Certificate Trust Settings.

**Running the Client and Server**
client: `npm run dev -- --experimental-https -H <ip-address>`
server: `npm run dev`
Use iPad to open up the url and check to make sure your photo is showing on server/__uploads.

## Screenshots (if applicable):

Please add any screenshots that illustrate your changes.

### CODE REVIEW

**Review by eriysd — CHANGES_REQUESTED** [review]
Can you handle the case where ssl certificate is undefined? Seems to crash atm. Thank you!

**Comment by viiiiiicccky** [comment]
> Can you handle the case where ssl certificate is undefined? Seems to crash atm. Thank you!

**Comment by viiiiiicccky** [comment]
> Can you handle the case where ssl certificate is undefined? Seems to crash atm. Thank you!

Hi Eri, server will now fallback to http instead of crashing if ssl key/certificate is unavailable (e.g. undefined in .env or defined paths not found). When running client and server in this case, one can still open https on client side, but photo won't be saved to server/__uploads.

**Review by eriysd — APPROVED** [review]
thanks vicky!

**Review by vicliu2001 — APPROVED** [review]
successfully created ssl certificate!

**Pull request merged**
