### PR TITLE
install dev dependency husky (testing branch for stacked changes)

### LINKED ISSUE #2: add prettier/eslint for typescript

### PR DESCRIPTION
**Pull request by natapokie**
## Description

**Fixes #2 and adds on to #20 **

(make sure to review #20 before reviewing this pr!)

Adding pre-commit hook with Husky (runs eslint and prettier) which formats code and checks for errors before committing.
adding lint-staged, makes sure that eslint and prettier are only run for files that are staged and not the entire repo.

Make sure to run `npm install` in root to use these changes

Also side note... to create stacked prs, you can set the `base` to the branch that you did your `git checkout -b` step from.
For example, this branch `2-husky-pre-commit-hooks` is a branch created from `2-add-prettiereslint-for-typescript` -- setting the base to `2-add-prettiereslint-for-typescript` (and not main) only shows the commits from this branch and not the branch i checked out from.
image

## Documentation Used

- [ ] [setting up husky](https://typicode.github.io/husky/)
- [ ] [lint-staged](https://www.npmjs.com/package/lint-staged)

## How To Test?

When you make a commit, you'll see something like the following, if Husky returns no errors, commit was successful,
image

### CODE REVIEW

**Review by viiiiiicccky — APPROVED** [review]
LGTM:)

**Review by vicliu2001 — APPROVED** [review]
looks good!

**Comment by natapokie** [comment]
@eriysd @vicliu2001 @viiiiiicccky sorry guys, resolved changes! would you be able to review again 😅

**Review by vicliu2001 — APPROVED** [review]
no problem!

**Review by eriysd — APPROVED** [review]
lgtm！

**Pull request merged**
